version: "3.8"

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - internal
  app:
    build: .
    command: python main.py
    volumes:
      - ./src:/app
    depends_on:
      - redis
    ports:
      - "5004:5000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - internal

  worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    volumes:
      - ./src:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - internal
networks:
  internal:
    driver: bridge
